### ISSUE TITLE
doing vanilla dom manipulation isn't ideal

### ISSUE THREAD

**Issue by reubengt** [fac24/week5-George-Hallie#29]
You don't want to be writing regular dom code in a react app

https://github.com/fac24/week5-George-Hallie/blob/5c5a5e2f0d2dc87dd72902f0c5de37300bf7e3f6/really-bad-movie/src/App.jsx#L25-L29

The react way of doing this would be to make showName a boolean state of true or false, and then conditionally render things in your jsx

```jsx
//in your component's return 
!showname && <form></form>
showname && <div id="showtime">Hello ${name}</div>
``

**Comment by vasystus** [comment]
Refactored, thank you!
